# Example: Using Caddy Gitea Pages behind nginx proxy
version: '3.8'

services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - caddy-gitea-pages
    networks:
      - proxy

  # Caddy with Gitea Pages (internal)
  caddy-gitea-pages:
    build:
      context: ../
      dockerfile: Dockerfile.caddy
    container_name: caddy-internal
    environment:
      - GITEA_URL=https://git.example.com
      - GITEA_TOKEN=${GITEA_TOKEN}
    volumes:
      - ./Caddyfile.internal:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - gitea_pages_cache:/var/cache/gitea-pages
    networks:
      - proxy
      - gitea
    # Only expose to internal network
    expose:
      - "8080"

  # Gitea service
  gitea:
    image: gitea/gitea:1.21
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea_data:/data
    networks:
      - gitea
    ports:
      - "3000:3000"

networks:
  proxy:
  gitea:

volumes:
  caddy_data:
  caddy_config:
  gitea_pages_cache:
  gitea_data: